## Q6- Concatenate following arrays along axis=0
x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])

In [1]:
import numpy as np

In [2]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print('Array 1 :','\n',x)
print('Array 2 :','\n',y)
print('Concatenate along rows :','\n',np.concatenate((x,y),axis=0))

Array 1 : 
 [[1 2]
 [3 4]]
Array 2 : 
 [[5 6]]
Concatenate along rows : 
 [[1 2]
 [3 4]
 [5 6]]
